[versions]
activity-compose = "1.8.0"
autoservice = "1.1.1"
autoserviceKsp = "1.1.0"
kotlin = "1.9.10"
ksp = "1.9.10-1.0.13"
versionsPlugin = "0.49.0"
kotlinPoet = "1.14.2"
agp = "8.1.2"
org-jetbrains-kotlin-android = "1.9.10"
junit = "4.13.2"
runner = "1.0.2"
espresso-core = "3.0.2"
appcompat-v7 = "28.0.0"
compose-bom = "2023.10.01"

[libraries]
autoservice-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version.ref = "autoserviceKsp" }
autoservice-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoservice" }
android-runtime = "com.google.android:android:4.1.1.4"
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
junit = "junit:junit:4.13.2"
kotlinPoet-core = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
kotlinPoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinPoet" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api ", version.ref = "ksp" }
plugin-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
junit-junit = { group = "junit", name = "junit", version.ref = "junit" }
runner = { group = "com.android.support.test", name = "runner", version.ref = "runner" }
espresso-core = { group = "com.android.support.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat-v7 = { group = "com.android.support", name = "appcompat-v7", version.ref = "appcompat-v7" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
material3 = { group = "androidx.compose.material3", name = "material3" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
vanniktech-publish = { id = "com.vanniktech.maven.publish", version = "0.25.3" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }