[versions]
incap = "1.0.0"
kotlin = "1.9.20"
#ksp =
versionsPlugin = "0.49.0"

[libraries]
android-runtime = "com.google.android:android:4.1.1.4"
android-gradlePlugin = "com.android.tools.build:gradle:8.1.2"
autoService = "com.google.auto.service:auto-service:1.1.1"
incap-runtime = { module = "net.ltgt.gradle.incap:incap", version.ref = "incap" }
incap-processor = { module = "net.ltgt.gradle.incap:incap-processor", version.ref = "incap" }
junit = "junit:junit:4.13.2"
kotlinpoet = "com.squareup:kotlinpoet:1.14.2"
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlinx-metadataJvm = "org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.7.0"

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsPlugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
vanniktech-publish = { id = "com.vanniktech.maven.publish", version = "0.25.3" }